// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPr5V4cxETrCnqnU_rLDN_vdgGu62h25M',
    appId: '1:968237430814:web:5cd3d317c1367973a0560f',
    messagingSenderId: '968237430814',
    projectId: 'comp5b-24-ee25d',
    authDomain: 'comp5b-24-ee25d.firebaseapp.com',
    storageBucket: 'comp5b-24-ee25d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDESO5f3hbCGn9cBoxa0DI10CBssHtzQ',
    appId: '1:968237430814:android:06ed0c03aafa78a3a0560f',
    messagingSenderId: '968237430814',
    projectId: 'comp5b-24-ee25d',
    storageBucket: 'comp5b-24-ee25d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtieQw618_eX1jnPVlKD6VEGr_YtKkp2w',
    appId: '1:968237430814:ios:dde55dbf4f7fbe69a0560f',
    messagingSenderId: '968237430814',
    projectId: 'comp5b-24-ee25d',
    storageBucket: 'comp5b-24-ee25d.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
